### ISSUE TITLE
asyncio has no attribute 'run'

### ISSUE THREAD

**Issue by docpindo** [DominikBuchner/BOLDigger-commandline#10]
Dear Dominik, sorry to boter you, I'm new in BOLDigger and I'm trying it for the first time. I'm using python 3.6, need I to upgrade it?
Login successful.
16:51:55: Requesting BOLD. This will take a while.
16:55:53: Downloading results.
Requesting BOLD:   0%|                                   | 0/31 [03:58<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/boldigger-cline", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/boldigger_cline/__main__.py", line 48, in main
    boldblast_coi.main(args.username, args.password, args.fasta_path, args.output_folder, args.batch_size)
  File "/usr/local/lib/python3.6/site-packages/boldigger_cline/boldblast_coi.py", line 28, in main
    tables = asyncio.run(as_session(links))
AttributeError: module 'asyncio' has no attribute 'run'

Thanks a lot for your help

**Comment by Anto007** [comment]
I ran into the same error as you when I had tried on python 3.6. But the good news is that the error disappeared for me when I re-ran the same on python 3.9

**Comment by DominikBuchner** [comment]
Yes, please upgrade to Python3.10 or higher, or directly use https://github.com/DominikBuchner/BOLDigger2.
best
Dominik
