### ISSUE TITLE
Batch size seems to not be optional

### ISSUE THREAD

**Issue by gjdury** [DominikBuchner/BOLDigger-commandline#11]
Dear Dominik, I am not sure if this warrants an issue, but when running BOLDigger without specifying the batch size the submitted fasta doesn't run. Someone on twitter was having the same issue. In case someone else sees this message, specifying the batch size (without brackets) fixed the problem. Seeing as the readme says the batch size is optional, this may be a new problem.

**Comment by DominikBuchner** [comment]
Hi, 
just saw this issue, sorry for the late reply. By default, BOLDigger will try the maximum batch size for the specific marker. This sometimes does not work when the database availability is low and/or the marker is really long. Therefor the batch size can optionally be reduced, however for most metabarcoding markers < 500 bp this is not necessary.

**Comment by DominikBuchner** [comment]
Please also check up https://github.com/DominikBuchner/BOLDigger2 were the batch size is automatically updated depending on network connection.
