### ISSUE TITLE
BOLD did not respond! Retrying

### ISSUE THREAD

**Issue by manonbayat** [DominikBuchner/BOLDigger-commandline#12]
Hi Dominik!

Since a few days I try to run boldigger-cline on a fasta file containing 638 sequences, and everything works well until the last 10% of the downloading. At the 13/14 batch, I just get this message for hours:

23:17:18: Downloading results.                                                  
23:17:18: Parsing html.                                                         
23:17:18: BOLD did not respond! Retrying.                                       
23:17:18: Requesting BOLD. This will take a while.                              
23:17:19: Downloading results.                                                  
23:17:19: Parsing html.                                                         
23:17:19: BOLD did not respond! Retrying.                                       
23:17:19: Requesting BOLD. This will take a while.                              
23:17:19: Downloading results.                                                  
23:17:19: Parsing html.                                                         
23:17:19: BOLD did not respond! Retrying.                                       
23:17:19: Requesting BOLD. This will take a while. 

I tried on two different computers, and with different internet connections, but I still get the same error. I don't think this is an error with my fasta file (uploaded below in .txt format).
Do you have an idea of what would it be?
Thank you very much!
Manon

[TANGO1_test_COI_OTU_rep.txt](https://github.com/DominikBuchner/BOLDigger-commandline/files/12800065/TANGO1_test_COI_OTU_rep.txt)

**Comment by cjfields** [comment]
@manonbayat I had this issue as well, and the error is pretty non-intuitive. It turns out both boldigger versions (GUI and command line) require a 'two-line' FASTA input, more specifically that the sequence line doesn't have line breaks.  You can get this using a tool like `seqkit` or `seqtk` pretty easily:

```
seqkit seq -w0 original.fasta > 2line.fasta
```

Once I had the above `boldigger` worked quite well.

**Comment by DominikBuchner** [comment]
Sorry for the late reply. Yes BOLDigger was only able to parse 2-line fasta files. 

https://github.com/DominikBuchner/BOLDigger2 will automatically handle this for you :)
