### ISSUE TITLE
Not initialize tkinter if running in command line mode?

### ISSUE THREAD

**Issue by voa257** [DominikBuchner/BOLDigger-commandline#14]
Hi, Dominik!

I've come across an issue with BOLDigger-commandline on our Ubuntu cluster. While it works smoothly on my personal setup, it hits a snag on the cluster.

It seems that BOLDigger-commandline tries to initiate tkinter on our "headless" cluster, which lacks a display environment. Consequently, it crashes during execution.

I understand it relies on the main BOLDigger setup, but is there a way to bypass the tkinter part when in command line mode? Perhaps catching the Tk instantiation exception could help?

Thanks,
Víctor

**Comment by DominikBuchner** [comment]
Ubuntu does not support tk natively, therefore you should be able to fix this with running:
`sudo apt-get install python3-tk`

I ran boldigger-cline on our ubuntu cluster as well, and the GUI is definitely not needed! BOLDigger2 no longer needs the GUI and should be more stable anyways, so please consider upgrading :) https://github.com/DominikBuchner/BOLDigger2
