### ISSUE TITLE
Running boldigger-cline -h produces error: cannot import name 'requests'

### ISSUE THREAD

**Issue by aminards** [DominikBuchner/BOLDigger-commandline#4]
Today I installed boldigger and boldigger-cline in Ubuntu on Windows 10.  Both seemed to install correctly.  Running boldigger-cline -h  gives this error:

Traceback (most recent call last):
File "/home/smith/.local/bin/boldigger-cline", line 5, in <module>
    from boldigger_cline.__main__ import main
  File "/home/smith/.local/lib/python3.8/site-packages/boldigger_cline/__main__.py", line 2, in <module>
    from boldigger_cline import boldblast_coi, boldblast_its, boldblast_rbcl, additional_data, first_hit, jamp_hit, digger_sort
  File "/home/smith/.local/lib/python3.8/site-packages/boldigger_cline/boldblast_its.py", line 8, in <module>
    from boldigger.boldblast_coi import slices, fasta_to_string, requests, fasta_rewrite
ImportError: cannot import name 'requests' from 'boldigger.boldblast_coi' (/home/smith/.local/lib/python3.8/site-packages/boldigger/boldblast_coi.py)

I am not sure how to fix this.

**Comment by 01Andrea01** [comment]
Same problem here. I just updated the GUI and the command line version. The GUI works, but the command line does not.

Traceback (most recent call last):
  File "/home/andrea/.local/bin/boldigger-cline", line 5, in <module>
    from boldigger_cline.__main__ import main
  File "/home/andrea/.local/lib/python3.8/site-packages/boldigger_cline/__main__.py", line 2, in <module>
    from boldigger_cline import boldblast_coi, boldblast_its, boldblast_rbcl, additional_data, first_hit, jamp_hit, digger_sort
  File "/home/andrea/.local/lib/python3.8/site-packages/boldigger_cline/boldblast_its.py", line 8, in <module>
    from boldigger.boldblast_coi import slices, fasta_to_string, requests, fasta_rewrite
ImportError: cannot import name 'requests' from 'boldigger.boldblast_coi' (/home/andrea/.local/lib/python3.8/site-packages/boldigger/boldblast_coi.py)

**Comment by pascalhabluetzel** [comment]
I had the same problem. It has to do with how the 'request' package is imported in the python scripts. Try modifying the boldblast_its.py and boldbalst_rbcl.py as follows:

change
```
from boldigger.boldblast_coi import slices, fasta_to_string, requests, fasta_rewrite
```

to
```
from boldigger.boldblast_coi import slices, fasta_to_string, fasta_rewrite
import requests
```

**Comment by naurasd** [comment]
Same problem, changing the scripts as described by @pascalhabluetzel did not work for me.

**Comment by DominikBuchner** [comment]
Will work on these issues once I have time. Fully booked at the moment.

**Comment by DominikBuchner** [comment]
This is a namespace problem. Old versions of BOLDigger defined a function called request, which are removed in the newer versions. This can be fixed temporarily by downgrading the BOLDigger GUI version. I will update boldigger-cline now to support the new functions.
