### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by naurasd** [DominikBuchner/BOLDigger-commandline#7]
Hi

I updated to the most recent version using

`pip install --upgrade boldigger-cline`

However, whenever I check the version of boldigger-cline, it says it's 1.0.0. Wasn't 2.0.0 the latest release?

Thanks

nauras

**Comment by DominikBuchner** [comment]
Since "-" is forbidden in python modules you'd have to install it with:

```
pip instal --upgrade boldigger_cline
```

**Comment by naurasd** [comment]
alright, got it. thanks. but the initial installation with "-" if i remember correctly?!

either way, the github page should probably be updated accordingly then.

thanks again for the help.

Nauras

**Comment by DominikBuchner** [comment]
done

**Comment by naurasd** [comment]
Hi, could you re-open this please?

I had boldigger_cline v2.1.2 installed and updated to v.2.2.0 according to your instructions above. See the last part of the installation output below:

```
Installing collected packages: boldigger, boldigger_cline
  Attempting uninstall: boldigger
    Found existing installation: boldigger 2.1.2
    Uninstalling boldigger-2.1.2:
      Successfully uninstalled boldigger-2.1.2
  Attempting uninstall: boldigger_cline
    Found existing installation: boldigger-cline 2.1.2
    Uninstalling boldigger-cline-2.1.2:
      Successfully uninstalled boldigger-cline-2.1.2
Successfully installed boldigger-2.2.0 boldigger_cline-2.2.0
```

However, when I check the installed version, it still says 1.0.0. See below:

```
(digger_env) -bash-4.2$ boldigger-cline --version
1.0.0
```

Any idea what's going on here?

**Comment by DominikBuchner** [comment]
Hi there,
my assumption would be that you have two different versions of python installed. One where pip is pointing to, the other where boldigger-cline is pointing to.
When calling boldigger-cline you can specify which python version to use with:
`pythonX.X -m boldigger-cline` (X.X refers to the version you want to call)

Can you please check if this is solving your issue?
Alternatively, to show which version you have installed you can also run
`pip freeze`
or 
`pipX.X freeze` (X.X) again for you version, to show all installed packages

**Comment by naurasd** [comment]
Thanks for the reply. Yes, something like this must be going on here.

Running bildigger-cline vwith miniconda. Have to figure this out with our HPC people. 

Thanks for pointing me in the right direction. Will close this for now, as this is probably not a boldigger-cline issue.

**Comment by naurasd** [comment]
To me it seems as there really is an issue here. While leaving the problem with boldigger-cline in conda on an HPC aside, I just wanted to check this on my personal machine.

I uninstalled boldigger-cline:
```
$ pip uninstall boldigger_cline
Found existing installation: boldigger-cline 2.2.0
Uninstalling boldigger-cline-2.2.0:
  Would remove:
    c:\users\nauras\programs\python\python39\lib\site-packages\boldigger_cline-2.2.0.dist-info\*
    c:\users\nauras\programs\python\python39\lib\site-packages\boldigger_cline\*
    c:\users\nauras\programs\python\python39\scripts\boldigger-cline.exe
Proceed (Y/n)? Y
  Successfully uninstalled boldigger-cline-2.2.0
```
Installed again:
```
$ pip install boldigger_cline
Collecting boldigger_cline
  Using cached boldigger_cline-2.2.0-py3-none-any.whl (16 kB)
Requirement already satisfied: boldigger>=2.2.0 in c:\users\nauras\programs\python\python39\lib\site-packages (from boldigger_cline) (2.2.0)
.
.
.
Installing collected packages: boldigger_cline
Successfully installed boldigger_cline-2.2.0
```
However, when checking the version, it still says 1.0.0:
```
$ boldigger-cline --version
1.0.0
```
I just have one version of python installed on my personal machine:
```
$ py -0
Installed Pythons found by C:\WINDOWS\py.exe Launcher for Windows
 -3.9-64 *
```

 So something must be up here. What am I misunderstanding?

Cheers

nauras

**Comment by DominikBuchner** [comment]
Fixed with version 2.2.1

**Comment by naurasd** [comment]
Ok, so I was using the latest version after all, it just showed the incorrect version?

**Comment by DominikBuchner** [comment]
Yes, now I still need to find a solution for the deviation between website and BOLDigger output which seems impossible to me, because they are retrieved from the same source. But I'll dig into this next week when I have time again :)
